### ISSUE TITLE
Java Error

### ISSUE THREAD

**Issue by sanaydevi** [klevis/DigitRecognizer#15]
Exception in thread "main" java.lang.NoSuchFieldException: theCaseInsensitiveEnvironment
	at java.lang.Class.getDeclaredField(Class.java:2070)
	at ramo.klevis.Run.setHadoopHomeEnvironmentVariable(Run.java:52)
	at ramo.klevis.Run.main(Run.java:28)

**Comment by klevis** [comment]
Hi @sanaydevi I feel free to comment usage of setHadoopHomeEnvironmentVariable. This method is needed in the case you are running the implementation with Spark MLib. Anyway there is a cleaner application [version  ](https://github.com/PacktPublishing/Java-Machine-Learning-for-Computer-Vision)as part of this course [Java Machine Learning For Computer Vision]( https://www.udemy.com/java-machine-learning-for-computer-vision/landing-page/)
